version: '3'

services:
  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server:latest
    restart: always
    volumes:
      - /data:/bitwarden/data
      - /ssl:/etc/certs
    env_file:
      - config.env
    ports:
      - '443:80'
