version: '3'

services:
  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server:latest
    restart: always
    ports:
      - '8080:80'
      - '8012:3012'
    volumes:
      - ./bitwarden/data:/data
