version: '3'

services:
  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server:latest
    restart: always
    ports:
      - '443:80'
    volumes:
      - ./bitwarden/data:/data
      - ./bitwarden/ssl/keys:/ssl
    environment:
      ROCKET_TLS={certs="/ssl/certs.cert",key="/ssl/key.key"}
