version: '3'

services:
  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server:latest
    restart: always
    volumes:
      - ./bitwarden/data:/data
      - ./bitwarden/ssl/keys:/ssl
    env_file:
      - config.env
    ports:
      - '443:80'
